languageCode = "zh-cn"
languageName = "Simplified Chinese"
weight = 1
title = "Rabinovich"
contentDir = "content/zh-cn"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"

[author]
name = "Rabinovich"
headline = "做王明易，做德胜难"
links = [
      { x-twitter = "https://twitter.com/PrcJack" },
      { email = "mailto:rabinovich83@outlook.com" }

]
